### ISSUE TITLE
IDs for new toys

### ISSUE THREAD

**Issue by wizard76** [metafetish/lovesense-docs#1]
From reverse engineering the Android apk, these are the toy IDs for the new toys:

Ambi is "l" (lowercase L)
Domi is "w"
Edge is "p"
Osci is "o"

There is also another toy, currently called secret which is "u".

**Comment by qdot** [comment]
Wow, thanks! Just curious, does the APK also list the nora/max/hush/lush as lower case, or upper case?

**Comment by wizard76** [comment]
All of the ids are lowercase in the APK.

**Comment by qdot** [comment]
Huh, ok, they come across as uppercase in the protocol and as bluetooth identifiers. Will update the doc. Thanks!

**Comment by qdot** [comment]
@wizard76 Oh, and one more thing, does the app have different service IDs and gatt characteristic IDs listed per toy, or does it look like everything uses the same set?

**Comment by wizard76** [comment]
I'm not familiar enough with this to give you a definitive answer. As best I can tell the only reference to service IDs is as follows:
    private static final String GACC_SERVICE = "00001800-0000-1000-8000-00805f9b34fb";
    private static final String GATT_SERVICE = "00001801-0000-1000-8000-00805f9b34fb";
Hopefully that answers the question.

**Comment by wizard76** [comment]
Here are some additional UUIDs from the Java Blutooth code:
        SERVICE_UUID_STR = "0000fff0-0000-1000-8000-00805f9b34fb";
        NOTIFY_CHARACTERISTIC_UUID_STR = "0000fff3-0000-1000-8000-00805f9b34fb";
        NOTIFY_DESCRIPTOR_UUID_STR = "00002902-0000-1000-8000-00805f9b34fb";
        MY_UUID = UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");

The support for the new toys is not complete so things may change.

Hopefully that gives you more insight into what is going on.

**Comment by qdot** [comment]
So, just found out the lush is BT4 instead of BT2 also, so that answered my question. The service and characteristic IDs (which is how you can tell what a BTLE device is and how to talk to it, basically) are the same across the lush and hush, I figure they'll be the same on the new toys too. Thanks for looking at that!
